sudo: true
language: php

php:
  - 7.1
  - nightly

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

install: composer install

cache:
  directories:
      - $HOME/.composer/cache

before_script:

script:
  - |
    docker-compose build > /dev/null 2>&1 &
    composer exec codecept run

notifications:
  email: false